export default {
    name:'announcements',
    title:'Announcements',
    type:'document',
    fields:[
        {
            name:"name",
            title:'Name',
            type:'string'
        },
        {
            name:'organisation',
            title:'Organisation',
            type:'string'
        },
        {
            name:'department',
            title:'Department',
            type:'string'
        },{
            name:'imageUrl',
            title:'ImageUrl',
            type:'image',
            options:{
                hotspot:true
            }
        },
        {
            name:'announce',
            title:'Announce',
            type:'string'
        },
        {
            name:'date',
            title:'Date',
            type:'string'
        }
    ]
}